### ISSUE TITLE
Expose API for checking corrupted class symbols

### ISSUE THREAD

**Issue by giiita** [lampepfl/dotty-feature-requests#216]
c.typecheck and c.parse have been lost.
The scalatest assertCompile and others can certainly achieve something similar by calling compiletime.testing.typeChecks directly at test time.

However, there may be cases in other libraries where typechecks are desperately needed.
The goal is to avoid a compile error due to typecheck failure.

For example, Symbol in ScalaTestAntTask 1 in scalatest refers to org.apache.tools, but since it is not bundled in scalatest, the compilation will fail when you access it with symbol.tree or something similar.

```
[error] -- Error: /src/dotty-test/src/test/scala/test/MacroCallSite.scala:16:25 
[error] 16 |      val result = macro[Foo]
[error]    |                   ^^^^^^^^^^^^^^^^^^
[error]    |undefined: new org.apache.tools.ant.Task # -1: TermRef(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class tools)),object ant),Task),<init>) at typer
```

If you want to test this dynamically, there is no way to do so because compiletime.test.typeChecks cannot be used.
As a general approach, Class.forName(name) can be used for checking, but the legitimacy of the symbol itself could not be checked because ClassNotFoundException is raised for module class or object.

https://contributors.scala-lang.org/t/how-to-check-for-broken-symbols-in-macro/5117

**Comment by giiita** [comment]
```
[error] -- Error: /Users/giiita/src/refuel/refuel-container/src/test/scala-3/refuel/inject/InjectorTest.scala:208:56 
[error] 208 |      val result1: Iterable[IterableDependency] = inject[List[IterableDependency]]
[error]     |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |undefined: new org.scalatools.testing.Runner2 # -1: TermRef(TypeRef(TermRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object org),object scalatools),object testing),Runner2),<init>) at typer
java.lang.Exception: Stack trace
  | => cat java.base/java.lang.Thread.dumpStack(Thread.java:1379)
	at dotty.tools.dotc.report$.error(report.scala:72)
	at dotty.tools.dotc.typer.ErrorReporting$.errorType(ErrorReporting.scala:34)
	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:290)
	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:19)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:106)
	at dotty.tools.dotc.ast.tpd$.Apply(tpd.scala:48)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1133)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1292)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$4(TreeUnpickler.scala:927)
	at dotty.tools.tasty.TastyReader.collectWhile(TastyReader.scala:137)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTemplate(TreeUnpickler.scala:930)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:857)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:776)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$Completer.complete(TreeUnpickler.scala:122)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:167)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
	at dotty.tools.dotc.core.Types$NamedType.info(Types.scala:2174)
	at dotty.tools.dotc.core.Types$TermLambda.dotty$tools$dotc$core$Types$TermLambda$$_$compute$1(Types.scala:3528)
	at dotty.tools.dotc.core.Types$TermLambda.dotty$tools$dotc$core$Types$TermLambda$$depStatus(Types.scala:3541)
	at dotty.tools.dotc.core.Types$TermLambda.dependencyStatus(Types.scala:3555)
	at dotty.tools.dotc.core.Types$TermLambda.resultType(Types.scala:3494)
	at dotty.tools.dotc.core.Types$TermLambda.resultType$(Types.scala:3486)
	at dotty.tools.dotc.core.Types$MethodType.resultType(Types.scala:3600)
	at dotty.tools.dotc.core.Types$TypeMap.mapOverLambda(Types.scala:5274)
	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5304)
	at dotty.tools.dotc.typer.Checking$NotPrivate$1.apply(Checking.scala:610)
	at dotty.tools.dotc.typer.Checking$.checkNoPrivateLeaks(Checking.scala:614)
	at dotty.tools.dotc.typer.TypeAssigner.avoidPrivateLeaks(TypeAssigner.scala:47)
	at dotty.tools.dotc.typer.TypeAssigner.avoidPrivateLeaks$(TypeAssigner.scala:19)
	at dotty.tools.dotc.typer.Typer.avoidPrivateLeaks(Typer.scala:106)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:889)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:776)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$Completer.complete(TreeUnpickler.scala:122)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:167)
	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
	at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:284)
	at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:227)
	at dotty.tools.dotc.quoted.reflect.FromSymbol$.defDefFromSym(FromSymbol.scala:46)
	at dotty.tools.dotc.quoted.reflect.FromSymbol$.definitionFromSym(FromSymbol.scala:21)
	at dotty.tools.dotc.quoted.reflect.FromSymbol$.$anonfun$4(FromSymbol.scala:35)
	at scala.collection.immutable.List.map(List.scala:250)
	at dotty.tools.dotc.quoted.reflect.FromSymbol$.classDef(FromSymbol.scala:35)
	at dotty.tools.dotc.quoted.reflect.FromSymbol$.definitionFromSym(FromSymbol.scala:18)
	at scala.quoted.runtime.impl.QuotesImpl$reflect$SymbolMethods$.tree(QuotesImpl.scala:2445)
	at scala.quoted.runtime.impl.QuotesImpl$reflect$SymbolMethods$.tree(QuotesImpl.scala:2445)
	at refuel.container.macros.internal.StaticDependencyExtractor$.liftedTree1$1(StaticDependencyExtractor.scala:159)
	at refuel.container.macros.internal.StaticDependencyExtractor$.isBrokenSymbol(StaticDependencyExtractor.scala:166)
	at refuel.container.macros.internal.StaticDependencyExtractor$.refuel$container$macros$internal$StaticDependencyExtractor$$$maybeCandidates(StaticDependencyExtractor.scala:137)
	at refuel.container.macros.internal.StaticDependencyExtractor$$anon$2.applyOrElse(StaticDependencyExtractor.scala:116)
	at scala.collection.immutable.List.collect(List.scala:275)
	at refuel.container.macros.internal.StaticDependencyExtractor$.$anonfun$1(StaticDependencyExtractor.scala:117)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
	at scala.collection.immutable.Vector.flatMap(Vector.scala:113)
	at refuel.container.macros.internal.StaticDependencyExtractor$.recursivePackageExplore(StaticDependencyExtractor.scala:119)
	at refuel.container.macros.internal.StaticDependencyExtractor$.run(StaticDependencyExtractor.scala:58)
	at refuel.container.macros.internal.StaticDependencyExtractor$.getList(StaticDependencyExtractor.scala:35)
	at refuel.container.macros.internal.StaticDependencyExtractor$.searchInjectionCandidates(StaticDependencyExtractor.scala:27)
	at refuel.container.macros.LazyAllInitializer$.all(LazyAllInitializer.scala:46)
	at refuel.container.macros.LazyAllInitializer$.$anonfun$2(LazyAllInitializer.scala:24)
	at refuel.container.macros.LazyAllInitializer$.$anonfun$adapted$2(LazyAllInitializer.scala:24)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:82)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1417)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:97)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1385)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1383)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1397)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1456)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1487)
	at scala.collection.immutable.List.mapConserve(List.scala:472)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1487)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1485)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1397)
	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:107)
	at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:122)
	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:61)
	at scala.quoted.runtime.impl.QuotesImpl.unpickleExpr(QuotesImpl.scala:2915)
	at refuel.container.macros.LazyAllInitializer$.init(LazyAllInitializer.scala:24)
	at refuel.container.macros.Macro$.dependentKindApplication(Macro.scala:30)
	at refuel.container.macros.Macro$.inject(Macro.scala:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at dotty.tools.dotc.transform.Splicer$Interpreter.interpretedStaticMethodCall$$anonfun$2$$anonfun$1(Splicer.scala:362)
	at dotty.tools.dotc.transform.Splicer$Interpreter.stopIfRuntimeException(Splicer.scala:422)
	at dotty.tools.dotc.transform.Splicer$Interpreter.interpretedStaticMethodCall$$anonfun$1(Splicer.scala:362)
	at dotty.tools.dotc.transform.Splicer$Interpreter.interpretTree(Splicer.scala:261)
	at dotty.tools.dotc.transform.Splicer$Interpreter.interpretTree$$anonfun$2(Splicer.scala:281)
	at dotty.tools.dotc.transform.Splicer$.$anonfun$2(Splicer.scala:56)
	at scala.Option.fold(Option.scala:263)
	at dotty.tools.dotc.transform.Splicer$.splice(Splicer.scala:56)
	at dotty.tools.dotc.typer.Inliner.dotty$tools$dotc$typer$Inliner$$expandMacro(Inliner.scala:1633)
	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1414)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2699)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2762)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1494)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2827)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2831)
	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2704)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2762)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1494)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2827)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2824)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2831)
	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:901)
	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:86)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1487)
	at scala.collection.immutable.List.mapConserve(List.scala:472)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1487)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1383)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:94)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1451)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:80)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:93)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:82)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:80)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1397)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:82)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1487)
	at scala.collection.immutable.List.mapConserve(List.scala:472)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1487)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1383)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:94)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1487)
	at scala.collection.immutable.List.mapConserve(List.scala:472)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1487)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1383)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:84)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1487)
	at scala.collection.immutable.List.mapConserve(List.scala:472)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1487)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1383)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:94)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1383)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:94)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:80)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1460)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:80)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1471)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:94)
	at dotty.tools.dotc.transform.Inlining$$anon$2.transform(Inlining.scala:72)
	at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
	at dotty.tools.dotc.transform.Inlining.run(Inlining.scala:44)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
	at dotty.tools.dotc.transform.Inlining.runOn(Inlining.scala:48)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:231)
	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
	at dotty.tools.dotc.Run.compile(Run.scala:150)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:457)
	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:412)
	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:399)
	at sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2362)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2319)
	at sbt.internal.io.Retry$.apply(Retry.scala:46)
	at sbt.internal.io.Retry$.apply(Retry.scala:28)
	at sbt.internal.io.Retry$.apply(Retry.scala:23)
	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2315)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
